---
title: 'Lesson 9'
subtitle: 'Data visualisation with R'
author: "Alessandro Bramucci"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  bookdown::pdf_document2:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(gapminder)
library(stargazer)
library(kableExtra)

```

# The most populous countries in 2007

```{r}

pop_countries <- gapminder %>% 
  filter(year == 2007) %>% 
  group_by(continent) %>%
  select(country, pop) %>% 
  arrange(desc(pop)) %>% 
  slice(1:3) %>% 
  ungroup()

pop_table <- pop_countries %>%
  select(country, pop) %>% 
  kbl(booktabs = TRUE,
      format.args = list(decimal.mark = ',',
                         big.mark = "\'"),
      caption = "The three most populous countries by continent in 2007. Source: Gapminder.",
      col.names = c("Country",
                    "Population")) %>% 
  pack_rows("Africa", 1, 3) %>%
  pack_rows("Americas", 4, 6) %>%
  pack_rows("Asia", 7, 9) %>%
  pack_rows("Europe", 10, 12) %>%
  pack_rows("Oceania", 13, 14) %>%
  kable_styling(latex_options = c("hold_position"))

pop_table

```

# Life expectancy and per capita GDP

From Figure \@ref(fig:figure) we can observe the existence of a positive relationship between per capita GDP growth and life expectancy.

```{r figure, fig.align = "center", out.width = '80%', out.height = '30%', fig.cap = "Relationship between per capita GDP growth and change in life expectancy, 1952-2007."}

df_graph <- gapminder %>% 
  group_by(country) %>% 
  mutate(pcGDPgr = c(NA, diff(gdpPercap))/lag(gdpPercap) * 100,
         dlifeExp = c(NA, diff(lifeExp))) %>% 
  drop_na()

p <- ggplot(df_graph, aes(y = dlifeExp,
                          x = pcGDPgr)) +
  geom_point(aes(color = continent)) + 
  geom_smooth(method = lm, se = FALSE) + 
  scale_color_manual(values = continent_colors) + 
  theme_bw() + 
  theme(legend.position = "bottom") +
  labs(color = NULL,
       y = "Change in life expectancy",
       x = "Per capita GDP growth",
       caption = "Source: Gapminder.")

p

```

## Econometric table

```{r, results = 'asis'}

reg <- lm(dlifeExp ~ pcGDPgr, data = df_graph)

# Regression table
stargazer(reg,
          header = FALSE,
          type = "latex",
          label = "tab:regressions",
          title = "Relationship between per capita GDP growth and life expectancy, 1952-2007.",
          dep.var.labels = c("dlifeExp"),
          covariate.labels = c("pcGDPgr"),
          keep.stat = c("n", "rsq"))

```
